import { GoogleGenAI, Chat, Type, Schema } from "@google/genai";
import { UserDetails, FeedbackReport } from "../types";

/**
 * Initializes the Google Generative AI instance with the provided API key.
 * @access private
 */
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * List of Gemini models ordered by priority for fallback mechanisms.
 * @constant
 */
const MODEL_PRIORITY_LIST = [
  'gemini-2.5-flash',
  'gemini-2.5-flash-lite',
];

/**
 * Locally cached working model identifier to prevent redundant health checks.
 * @type {string | null}
 */
let activeModel: string | null = null;

/**
 * Determines if a given error is related to API quota exhaustion or rate limiting.
 * 
 * @param {any} error - The error object caught during an API call.
 * @returns {boolean} True if the error indicates a quota or resource exhaustion issue.
 */
const isErrorQuotaRelated = (error: any): boolean => {
  const msg = (error.message || JSON.stringify(error)).toLowerCase();
  return (
    error.status === 429 || 
    error.code === 429 || 
    msg.includes('429') || 
    msg.includes('quota') || 
    msg.includes('resource_exhausted') ||
    msg.includes('exhausted')
  );
};

/**
 * Performs a health check on available models in the priority list and returns the first operational one.
 * Implements a caching mechanism to avoid re-testing models during an active session.
 * 
 * @async
 * @returns {Promise<string>} The identifier of the confirmed operational model.
 */
const getWorkingModel = async (): Promise<string> => {
  if (activeModel) return activeModel;

  console.log("Checking for available Gemini models...");
  
  for (const model of MODEL_PRIORITY_LIST) {
    try {
      console.log(`Testing model quota: ${model}...`);
      await ai.models.generateContent({
        model: model,
        contents: [{ parts: [{ text: 'hi' }] }],
        config: { 
          maxOutputTokens: 1,
        }
      });
      
      console.log(`✅ Model operational: ${model}`);
      activeModel = model;
      return model;
    } catch (error: any) {
      if (isErrorQuotaRelated(error)) {
        console.warn(`⚠️ Model ${model} QUOTA EXCEEDED. Switching to next...`);
      } else {
        console.warn(`⚠️ Model ${model} failed check.`, error);
      }
    }
  }

  console.log("⚠️ All checks failed, defaulting to gemini-2.5-flash");
  return 'gemini-2.5-flash';
};

/**
 * Initializes a new interview session with the AI interviewer "Ava".
 * Configures the system instructions based on the candidate's professional profile.
 * 
 * @async
 * @param {UserDetails} userDetails - The profile and context of the candidate.
 * @returns {Promise<Chat>} A promise resolving to the initialized Google GenAI Chat instance.
 */
export const startInterviewSession = async (userDetails: UserDetails): Promise<Chat> => {
  const CHAT_MODEL = await getWorkingModel();
  
  console.log(`Starting session with model: ${CHAT_MODEL}`);

  const systemInstruction = `You are **Ava**, an expert HR interviewer and career coach conducting a video interview.
  
  CANDIDATE DETAILS:
  - Name: ${userDetails.name || 'Candidate'}
  - Role: ${userDetails.targetRole}
  - Industry: ${userDetails.industry}
  - Level: ${userDetails.experienceLevel}

  INSTRUCTIONS:
  1. Act as a professional interviewer named Ava. Be polite, encouraging, but rigorous.
  2. Ask ONE question at a time.
  3. LANGUAGE & SPEECH HANDLING:
     - Conduct the interview strictly in ENGLISH.
     - The candidate is using real-time voice-to-text.
     - Understand the core meaning behind disfluencies like "aa", "hh", "umm".
  4. **ACTIVE VISUAL MONITORING**:
     - Analyze body language, posture, and eye contact from provided images.
     - Politely mention issues (e.g., slouching, looking away) before asking the next question.
  5. RESPONSE STYLE:
     - Keep spoken responses short (max 2-3 sentences).
  
  Start by welcoming the candidate in English and asking the first question.`;

  const chat = ai.chats.create({
    model: CHAT_MODEL,
    config: {
      systemInstruction: systemInstruction,
    },
  });

  return chat;
};

/**
 * Sends a multimodal message (text and/or image) to the active AI interview session.
 * Handles specialized error cases including network instability and quota exhaustion.
 * 
 * @async
 * @param {Chat} chat - The active Chat session instance.
 * @param {string} text - The transcribed text input from the candidate.
 * @param {string | null} [imageBase64] - Optional base64 encoded video snapshot.
 * @returns {Promise<string>} The textual response generated by the AI interviewer.
 */
export const sendMessageWithVideo = async (
  chat: Chat, 
  text: string, 
  imageBase64?: string | null
): Promise<string> => {
  const parts: any[] = [];
  
  if (text && text.trim().length > 0) {
    parts.push({ text });
  } else {
    parts.push({ text: "[User nodded or provided non-verbal input]" });
  }

  if (imageBase64) {
    parts.push({
      inlineData: {
        mimeType: 'image/jpeg',
        data: imageBase64
      }
    });
  }

  try {
    const response = await chat.sendMessage({
      message: parts
    });
    return response.text || "";
  } catch (error: any) {
    console.error("Gemini API Error:", error);

    const errorObj = error.error || error;
    const message = error.message || errorObj.message || JSON.stringify(error);

    if (message.includes('xhr error') || message.includes('Rpc failed') || message.includes('fetch failed') || message.includes('NetworkError')) {
       return "Error: Network connection unstable. I couldn't receive your message. Please try sending again.";
    }

    if (isErrorQuotaRelated(error)) {
       activeModel = null;
       return "Error: Daily quota exceeded for this model. Please tap Retry/Send to switch to the backup model.";
    }

    if (error.status === 404 || message.includes('404')) {
       activeModel = null;
       return "Error: AI Service temporarily unavailable (404). Please try again.";
    }
    
    return "Error: Something went wrong. Please try again.";
  }
};

/**
 * Initializes the interview by providing the candidate's resume and initial profile context.
 * 
 * @async
 * @param {Chat} chat - The Chat session instance.
 * @param {UserDetails} userDetails - The candidate's details including resume data.
 * @returns {Promise<string>} The first question or acknowledgement from the AI.
 */
export const sendInitialMessageWithResume = async (chat: Chat, userDetails: UserDetails): Promise<string> => {
  const parts: any[] = [];
  
  let text = `I am ready for the interview. My name is ${userDetails.name}. Role: ${userDetails.targetRole}.`;
  if (userDetails.jobDescription) text += `\nJob Description Context: ${userDetails.jobDescription}`;
  
  parts.push({ text });

  if (userDetails.resumeBase64 && userDetails.resumeMimeType) {
    parts.push({
      inlineData: {
        mimeType: userDetails.resumeMimeType,
        data: userDetails.resumeBase64
      }
    });
  }

  try {
    const response = await chat.sendMessage({
      message: parts
    });
    return response.text || "";
  } catch (error: any) {
    console.error("Initial Connection Error:", error);
    const errorObj = error.error || error;
    const message = error.message || errorObj.message || JSON.stringify(error);

    if (message.includes('xhr error') || message.includes('Rpc failed') || message.includes('fetch failed')) {
       return "Error: Network connection failed. Please check your internet.";
    }

    if (error.status === 404) {
       activeModel = null;
       return "Error: Model not found (404). Please check configuration.";
    }
    
    if (isErrorQuotaRelated(error)) {
       activeModel = null;
       return "Error: Quota exceeded. Please try again to switch models.";
    }
    
    return `Error: Failed to initialize. (${message.substring(0, 100)}...)`;
  }
};

/**
 * Generates a comprehensive analytical feedback report based on the interview transcript and resume.
 * Utilizes structural JSON output with a strictly defined schema for consistency.
 * 
 * @async
 * @param {Array<{role: string, text: string}>} transcript - The sequential history of the interview conversation.
 * @param {UserDetails} userDetails - The candidate's metadata and professional background.
 * @returns {Promise<FeedbackReport>} A structured report containing scores, categorical feedback, and growth roadmaps.
 * @throws {Error} If the report generation fails or the API produces invalid data.
 */
export const generateDetailedFeedback = async (
  transcript: { role: string; text: string }[],
  userDetails: UserDetails
): Promise<FeedbackReport> => {
  const ANALYSIS_MODEL = await getWorkingModel();
  const transcriptText = transcript.map(t => `${t.role.toUpperCase()}: ${t.text}`).join('\n\n');

  const prompt = `
    Analyze this mock video interview session and the candidate's resume.
    
    Candidate: ${userDetails.name}
    Role: ${userDetails.targetRole}
    Experience: ${userDetails.experienceLevel}
    
    TRANSCRIPT:
    ${transcriptText}

    Generate a detailed structured JSON report covering the interview performance, ATS resume analysis, and a personalized learning roadmap.
  `;

  const parts: any[] = [{ text: prompt }];

  if (userDetails.resumeBase64 && userDetails.resumeMimeType) {
    parts.push({
      inlineData: {
        mimeType: userDetails.resumeMimeType,
        data: userDetails.resumeBase64
      }
    });
  }

  const feedbackSchema: Schema = {
    type: Type.OBJECT,
    properties: {
      overallSummary: { type: Type.STRING },
      overallScore: { type: Type.INTEGER, description: "Interview performance only. 0 if no answers." },
      categoryFeedback: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            category: { type: Type.STRING },
            score: { type: Type.INTEGER, description: "Score out of 100" },
            strengths: { type: Type.ARRAY, items: { type: Type.STRING } },
            improvements: { type: Type.ARRAY, items: { type: Type.STRING } },
          },
          required: ["category", "score", "strengths", "improvements"]
        }
      },
      questionFeedback: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            question: { type: Type.STRING },
            userAnswer: { type: Type.STRING },
            goodPoints: { type: Type.STRING },
            missingPoints: { type: Type.STRING },
            improvedExample: { type: Type.STRING },
          },
          required: ["question", "userAnswer", "goodPoints", "missingPoints", "improvedExample"]
        }
      },
      resumeAnalysis: {
        type: Type.OBJECT,
        properties: {
          atsScore: { type: Type.INTEGER, description: "ATS Score out of 100 based on resume file only" },
          strengths: { type: Type.ARRAY, items: { type: Type.STRING } },
          weaknesses: { type: Type.ARRAY, items: { type: Type.STRING } },
          suggestions: { type: Type.ARRAY, items: { type: Type.STRING } },
        },
        required: ["atsScore", "strengths", "weaknesses", "suggestions"]
      },
      skillGaps: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            skill: { type: Type.STRING },
            status: { type: Type.STRING, enum: ["strong", "weak", "missing"] },
            category: { type: Type.STRING, enum: ["technical", "domain", "soft"] }
          },
          required: ["skill", "status", "category"]
        }
      },
      learningRoadmap: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            skill: { type: Type.STRING },
            action: { type: Type.STRING },
            resourceType: { type: Type.STRING }
          },
          required: ["skill", "action", "resourceType"]
        }
      }
    },
    required: ["overallSummary", "overallScore", "categoryFeedback", "questionFeedback", "resumeAnalysis", "skillGaps", "learningRoadmap"]
  };

  try {
    const response = await ai.models.generateContent({
      model: ANALYSIS_MODEL,
      contents: { parts },
      config: {
        responseMimeType: 'application/json',
        responseSchema: feedbackSchema
      }
    });

    let text = response.text || "{}";
    text = text.replace(/```json/g, '').replace(/```/g, '').trim();
    const firstBrace = text.indexOf('{');
    const lastBrace = text.lastIndexOf('}');
    if (firstBrace !== -1 && lastBrace !== -1) {
       text = text.substring(firstBrace, lastBrace + 1);
    }

    return JSON.parse(text) as FeedbackReport;
  } catch (e) {
    console.error("Analysis failed", e);
    throw new Error("Failed to generate feedback report. Please ensure your transcript is sufficient.");
  }
};
