import React, { useEffect, useState } from 'react';
import { UserDetails, Message, FeedbackReport } from '../types';
import { generateDetailedFeedback } from '../services/geminiService';
import { ResponsiveContainer, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar } from 'recharts';
import { CheckCircle, AlertTriangle, BookOpen, Copy, Loader2, Video, FileText, Star, RefreshCw, ChevronRight } from 'lucide-react';

interface FeedbackStepProps {
  userDetails: UserDetails;
  transcript: Message[];
  onRestart: () => void;
}

const FeedbackStep: React.FC<FeedbackStepProps> = ({ userDetails, transcript, onRestart }) => {
  const [report, setReport] = useState<FeedbackReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const fetchReport = async () => {
      try {
        const result = await generateDetailedFeedback(transcript, userDetails);
        setReport(result);
        
        const historyItem = {
           id: Date.now().toString(),
           date: new Date().toISOString(),
           role: userDetails.targetRole,
           score: result.overallScore
        };
        const existing = JSON.parse(localStorage.getItem('interview_history') || '[]');
        localStorage.setItem('interview_history', JSON.stringify([historyItem, ...existing].slice(0, 10)));

      } catch (err) {
        console.error(err);
        setError("Failed to generate report. Please try again.");
      } finally {
        setLoading(false);
      }
    };
    fetchReport();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleCopy = () => {
    if (!report) return;
    const text = `Interview Report - ${userDetails.targetRole}\nScore: ${report.overallScore}/100\nATS Score: ${report.resumeAnalysis.atsScore}/100\nSummary: ${report.overallSummary}\n\nGenerated by InterviewPilot`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] text-slate-800 animate-fadeIn px-4 text-center">
        <div className="relative">
          <div className="w-20 h-20 border-4 border-slate-100 border-t-indigo-600 rounded-full animate-spin"></div>
          <div className="absolute inset-0 flex items-center justify-center">
            <Loader2 className="w-8 h-8 text-indigo-600 animate-pulse" />
          </div>
        </div>
        <h3 className="text-2xl font-bold mt-8 tracking-tight text-slate-900">Generating Analysis</h3>
        <p className="max-w-md text-center mt-3 text-slate-500">AI is analyzing your video presence, speech clarity, and resume alignment...</p>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[50vh] p-8">
        <div className="bg-red-50 p-6 rounded-2xl border border-red-100 max-w-md w-full text-center shadow-sm">
          <div className="w-12 h-12 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
             <AlertTriangle className="w-6 h-6 text-red-600" />
          </div>
          <h3 className="text-lg font-bold text-slate-900 mb-2">Analysis Failed</h3>
          <p className="text-slate-600 mb-6 text-sm">{error || "Something went wrong during the analysis."}</p>
          <button 
            onClick={onRestart} 
            className="w-full px-4 py-3 bg-white border border-slate-200 text-slate-700 font-medium rounded-xl hover:bg-slate-50 transition shadow-sm"
          >
            Try Again
          </button>
        </div>
      </div>
    );
  }

  // Adjust radar domain to 100
  const chartData = report.categoryFeedback.map(c => ({ subject: c.category, A: c.score, fullMark: 100 }));

  const getScoreColor = (score: number) => {
    if (score >= 80) return 'text-green-700 bg-green-50 border-green-200';
    if (score >= 60) return 'text-amber-700 bg-amber-50 border-amber-200';
    return 'text-red-700 bg-red-50 border-red-200';
  };

  return (
    <div className="max-w-6xl mx-auto pb-12 animate-fadeIn w-full">
      {/* Toast Notification */}
      {copied && (
        <div className="fixed bottom-10 left-1/2 -translate-x-1/2 bg-slate-900 text-white px-6 py-3 rounded-full shadow-2xl z-50 flex items-center gap-3 animate-fadeIn w-max max-w-[90%] backdrop-blur-md border border-white/10">
          <CheckCircle size={18} className="text-green-400 shrink-0" />
          <span className="font-medium">Report copied to clipboard</span>
        </div>
      )}

      {/* Header Banner */}
      <div className="bg-slate-900 text-white rounded-3xl shadow-2xl overflow-hidden mb-8 mx-4 md:mx-0 relative">
        {/* Background Gradients */}
        <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-indigo-600/30 rounded-full mix-blend-screen filter blur-[100px] -translate-y-1/2 translate-x-1/3"></div>
        <div className="absolute bottom-0 left-0 w-[300px] h-[300px] bg-blue-600/20 rounded-full mix-blend-screen filter blur-[80px] translate-y-1/2 -translate-x-1/4"></div>
        
        <div className="relative z-10 p-6 md:p-10 flex flex-col md:flex-row justify-between items-start md:items-end gap-8">
          <div className="space-y-4 max-w-2xl">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-green-500/10 border border-green-500/20 text-green-400 text-xs font-semibold uppercase tracking-wider">
              <CheckCircle size={12} /> Analysis Complete
            </div>
            <div>
               <h1 className="text-3xl md:text-4xl font-extrabold tracking-tight text-white mb-2">
                 {userDetails.targetRole}
               </h1>
               <div className="flex flex-wrap items-center gap-3 text-slate-400 text-sm">
                 <span className="flex items-center gap-1.5"><Star size={14} className="text-yellow-500"/> {userDetails.experienceLevel}</span>
                 <span className="w-1 h-1 bg-slate-600 rounded-full"></span>
                 <span>{userDetails.language}</span>
                 <span className="w-1 h-1 bg-slate-600 rounded-full"></span>
                 <span>{new Date().toLocaleDateString()}</span>
               </div>
            </div>
          </div>
          
          <div className="flex flex-row md:flex-col items-center md:items-end justify-between w-full md:w-auto gap-4 md:gap-1">
             <div className="text-left md:text-right">
               <div className="text-xs text-indigo-200 uppercase tracking-widest font-bold mb-1">Overall Score</div>
               {/* SCORE ALIGNMENT FIX */}
               <div className="flex items-baseline gap-1.5 justify-start md:justify-end">
                  <span className={`text-5xl md:text-6xl font-black tracking-tighter ${report.overallScore >= 70 ? 'text-green-400' : report.overallScore >= 50 ? 'text-yellow-400' : 'text-red-400'}`}>
                    {report.overallScore}
                  </span>
                  <span className="text-xl md:text-2xl font-medium text-slate-500/80">/100</span>
               </div>
             </div>
             
             <div className="flex gap-3 mt-2 md:mt-4">
                <button onClick={handleCopy} className="p-3 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl transition text-white/80 hover:text-white" title="Copy Report">
                    <Copy size={20} />
                </button>
                <button onClick={onRestart} className="px-5 py-3 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-bold shadow-lg shadow-indigo-900/50 transition flex items-center gap-2 text-sm">
                    <RefreshCw size={18} /> New Session
                </button>
             </div>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 md:gap-8 mx-4 md:mx-0">
        
        {/* Left Column: Visuals & Resume (4 cols) */}
        <div className="lg:col-span-4 space-y-6 md:space-y-8">
           
           {/* Radar Chart Card */}
           <div className="bg-white p-6 rounded-3xl shadow-sm border border-slate-100 flex flex-col h-[340px]">
             <h3 className="font-bold text-slate-800 mb-2 flex items-center gap-2">
                <Star size={18} className="text-indigo-600"/> Performance Radar
             </h3>
             <div className="flex-1 -ml-6 w-[115%]">
                <ResponsiveContainer width="100%" height="100%">
                  <RadarChart cx="50%" cy="50%" outerRadius="70%" data={chartData}>
                    <PolarGrid stroke="#e2e8f0" />
                    <PolarAngleAxis dataKey="subject" tick={{fontSize: 10, fill: '#64748b', fontWeight: 600}} />
                    <PolarRadiusAxis angle={30} domain={[0, 100]} tick={false} axisLine={false} />
                    <Radar name="Score" dataKey="A" stroke="#4f46e5" strokeWidth={3} fill="#4f46e5" fillOpacity={0.15} />
                  </RadarChart>
                </ResponsiveContainer>
             </div>
           </div>
           
           {/* Resume & ATS Analysis Card */}
           <div className="bg-white rounded-3xl shadow-sm border border-slate-100 relative overflow-hidden group">
             <div className="absolute top-0 right-0 w-32 h-32 bg-gradient-to-br from-blue-50 to-indigo-50 rounded-bl-[100px] -mr-0 -mt-0 opacity-80 group-hover:scale-110 transition-transform duration-500"></div>
             
             <div className="p-6 relative z-10">
                <div className="flex items-center justify-between mb-6">
                    <div>
                        <h3 className="font-bold text-slate-800 flex items-center gap-2">
                           <FileText size={18} className="text-blue-600" />
                           Resume Health
                        </h3>
                        <p className="text-xs text-slate-500 mt-1">ATS Compatibility Check</p>
                    </div>
                    <div className="text-right">
                       <div className={`text-3xl font-black ${report.resumeAnalysis.atsScore >= 75 ? 'text-green-600' : 'text-amber-600'}`}>
                          {report.resumeAnalysis.atsScore}
                       </div>
                       <div className="text-[10px] font-bold text-slate-400 uppercase tracking-wide">ATS Score</div>
                    </div>
                </div>

                <div className="space-y-5">
                   {/* Strengths */}
                   <div className="space-y-2">
                      <h4 className="text-[11px] font-bold uppercase tracking-wider text-green-700/70 flex items-center gap-1.5">
                         <CheckCircle size={12}/> Strong Matches
                      </h4>
                      <ul className="space-y-2">
                         {report.resumeAnalysis.strengths.slice(0, 3).map((s, i) => (
                            <li key={i} className="text-xs text-slate-700 bg-green-50/50 p-2 rounded-lg border border-green-100/50">
                               {s}
                            </li>
                         ))}
                      </ul>
                   </div>
                   
                   {/* Weaknesses */}
                   <div className="space-y-2">
                      <h4 className="text-[11px] font-bold uppercase tracking-wider text-amber-700/70 flex items-center gap-1.5">
                         <AlertTriangle size={12}/> Missing Keywords
                      </h4>
                      <ul className="space-y-2">
                         {report.resumeAnalysis.weaknesses.slice(0, 3).map((w, i) => (
                            <li key={i} className="text-xs text-slate-700 bg-amber-50/50 p-2 rounded-lg border border-amber-100/50">
                               {w}
                            </li>
                         ))}
                      </ul>
                   </div>
                   
                   {/* AI Tip */}
                   <div className="bg-gradient-to-r from-blue-50 to-indigo-50 p-4 rounded-xl border border-blue-100 mt-2">
                      <h5 className="text-xs font-bold text-blue-800 mb-1.5 flex items-center gap-1.5"><Star size={12} fill="currentColor" /> Quick Fix</h5>
                      <p className="text-xs text-blue-900/80 leading-relaxed font-medium">
                         {report.resumeAnalysis.suggestions[0]}
                      </p>
                   </div>
                </div>
             </div>
           </div>

           {/* Executive Summary */}
           <div className="bg-slate-800 text-slate-200 p-6 rounded-3xl shadow-lg border border-slate-700">
             <h3 className="font-bold text-white mb-4 text-sm uppercase tracking-wide opacity-80">Executive Summary</h3>
             <p className="text-sm leading-relaxed text-slate-300 font-light">{report.overallSummary}</p>
           </div>
        </div>

        {/* Middle/Right: Details (8 cols) */}
        <div className="lg:col-span-8 space-y-6 md:space-y-8">
          
          {/* Detailed Scores Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
             {report.categoryFeedback.map((cat, idx) => (
               <div key={idx} className="bg-white p-5 rounded-2xl border border-slate-100 shadow-sm hover:shadow-md transition-shadow group">
                 <div className="flex justify-between items-start mb-4">
                   <span className="font-bold text-slate-700 flex items-center gap-2.5">
                     <span className="p-2 bg-slate-50 rounded-lg group-hover:bg-indigo-50 transition-colors">
                        {cat.category === 'Visual Presence & Confidence' ? <Video size={16} className="text-purple-600" /> : <Star size={16} className="text-indigo-600" />}
                     </span>
                     {cat.category}
                   </span>
                   <span className={`text-xs font-bold px-2.5 py-1 rounded-full border ${getScoreColor(cat.score)}`}>
                     {cat.score} / 100
                   </span>
                 </div>
                 
                 <div className="space-y-3">
                   {cat.strengths.slice(0,1).map((s, i) => (
                     <div key={i} className="flex gap-2 items-start text-xs text-slate-600">
                       <CheckCircle size={14} className="text-green-500 shrink-0 mt-0.5" />
                       <span>{s}</span>
                     </div>
                   ))}
                   {cat.improvements.slice(0,1).map((s, i) => (
                     <div key={i} className="flex gap-2 items-start text-xs text-slate-600">
                       <AlertTriangle size={14} className="text-amber-500 shrink-0 mt-0.5" />
                       <span>{s}</span>
                     </div>
                   ))}
                 </div>
               </div>
             ))}
          </div>

          {/* Q&A Breakdown */}
          <div className="bg-white rounded-3xl shadow-sm border border-slate-100 overflow-hidden">
             <div className="p-6 border-b border-slate-100 bg-slate-50/30 flex items-center gap-3">
               <div className="p-2 bg-indigo-100 text-indigo-600 rounded-lg">
                  <BookOpen size={20} />
               </div>
               <div>
                  <h3 className="font-bold text-slate-800">Transcript & Critique</h3>
                  <p className="text-xs text-slate-500">Detailed question-by-question breakdown</p>
               </div>
             </div>
             <div className="divide-y divide-slate-100">
               {report.questionFeedback.map((q, i) => (
                 <div key={i} className="p-6 hover:bg-slate-50/50 transition duration-300">
                    <div className="flex gap-4 mb-4">
                      <div className="text-xs font-bold bg-slate-100 text-slate-500 px-2.5 py-1 rounded-lg h-fit shrink-0 border border-slate-200">
                        Q{i+1}
                      </div>
                      <p className="font-bold text-slate-800 text-sm md:text-base leading-snug">{q.question}</p>
                    </div>
                    
                    <div className="pl-0 md:pl-12 space-y-4">
                      <div className="bg-slate-50 border border-slate-100 p-4 rounded-xl text-sm text-slate-600 italic relative">
                        <div className="absolute -top-2 left-4 px-2 bg-slate-50 text-[10px] font-bold text-slate-400 uppercase tracking-wider">Your Answer</div>
                        "{q.userAnswer}"
                      </div>
                      
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div className="bg-green-50/50 p-3 rounded-xl border border-green-100/50">
                          <span className="text-green-700 font-bold text-xs uppercase block mb-1.5 flex items-center gap-1.5"><CheckCircle size={12}/> Good</span>
                          <span className="text-slate-600 text-xs leading-relaxed">{q.goodPoints}</span>
                        </div>
                        <div className="bg-amber-50/50 p-3 rounded-xl border border-amber-100/50">
                           <span className="text-amber-700 font-bold text-xs uppercase block mb-1.5 flex items-center gap-1.5"><AlertTriangle size={12}/> Missing</span>
                           <span className="text-slate-600 text-xs leading-relaxed">{q.missingPoints}</span>
                        </div>
                      </div>

                      <div className="bg-indigo-50 p-4 rounded-xl border border-indigo-100/80">
                        <span className="text-indigo-700 font-bold text-xs uppercase block mb-2">💡 Improved Answer Example</span>
                        <p className="text-indigo-900/90 text-sm leading-relaxed">{q.improvedExample}</p>
                      </div>
                    </div>
                 </div>
               ))}
             </div>
          </div>
          
          {/* Learning Roadmap */}
          <div className="bg-slate-900 text-white p-6 md:p-8 rounded-3xl shadow-xl relative overflow-hidden">
             <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-500 rounded-full mix-blend-overlay filter blur-[60px] opacity-20"></div>
            
             <h3 className="font-bold text-lg mb-6 relative z-10">Recommended Learning Path</h3>
             <div className="grid grid-cols-1 md:grid-cols-2 gap-4 relative z-10">
              {report.learningRoadmap.slice(0, 4).map((item, i) => (
                <div key={i} className="flex gap-4 items-start bg-white/5 p-4 rounded-2xl border border-white/10 hover:bg-white/10 transition">
                   <div className="w-8 h-8 rounded-full bg-indigo-600 flex items-center justify-center font-bold text-sm shrink-0 shadow-lg shadow-indigo-500/30">
                     {i+1}
                   </div>
                   <div>
                     <h4 className="font-bold text-sm text-indigo-100">{item.skill}</h4>
                     <p className="text-xs text-slate-400 mt-1 leading-relaxed">{item.action}</p>
                     <div className="mt-2.5 inline-flex px-2 py-1 bg-white/10 rounded-md text-[10px] uppercase font-bold tracking-wide text-white/70">
                       {item.resourceType}
                     </div>
                   </div>
                </div>
              ))}
            </div>
          </div>

        </div>
      </div>
    </div>
  );
};

export default FeedbackStep;